server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore_books_db?serverTimezone=UTC
    username: ashish
    password: Ashish$1
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

app:
  s3:
    bucket-name: ${S3_BUCKET_NAME:}
    region: ${AWS_REGION:us-west-2}

jwt:
  secret: 3b796f1d-02e9-4263-a411-ceb6e5532239

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans


logging:
  level:
    org.springframework.web: DEBUG
