server:
  port: 8088

spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore_analytics_db?serverTimezone=UTC
    username: ${DB_USERNAME:ashish}
    password: ${DB_PASSWORD:Ashish$1}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

jwt:
  secret: ${JWT_SECRET:3b796f1d-02e9-4263-a411-ceb6e5532239}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.bookstore.analytics: INFO
